name: env
channels:
   - conda-forge
   - anaconda
dependencies:
   - python=3.11.4
   - conda-build

   # essential
   - root=6.28.4
   - cmake=3.26.4

   # formatting
   - clang-format=14.0.6

   # tools
   - numpy>=1.19.0
   - astropy>=4.0
   - scipy>=1.6
   - pandas>=1.1.0
   - matplotlib>=3.3.0
   - ipykernel>=6.16.0

  