#include "analysis.hpp"
#include "manager.hpp"

#include "correlations/custom_correlation.hpp"
#include "cuts/custom_event_cut.hpp"
#include "cuts/custom_event_monitor.hpp"
#include "cuts/custom_pair_cut.hpp"
#include "cuts/custom_pair_monitor.hpp"
#include "cuts/custom_track_cut.hpp"
#include "cuts/custom_track_monitor.hpp"
#include "readers/custom_reader.hpp"
