name: all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    caching-example:
      name: Caching
      runs-on: "ubuntu-latest"
      steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('./environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
            activate-environment: ./env
            channel-priority: strict
            environment-file: ./environment.yml
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: check conda
        shell: bash -el {0}
        run: |
          conda info
          conda list
    
      - name: check
        shell: bash -el {0}
        run: |
          conda activate ./env
          root-config --version
          cmake --version
