name: all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      uses: actions/cache@v3
      env:
          CACHE_NUMBER: 0
      with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('./environment.yml') }}
        

    - uses: conda-incubator/setup-miniconda@v2
      with:
          miniconda-version: "latest"
          channel-priority: strict
          activate-environment: ./env
          environment-file: ./environment.yml
          use-only-tar-bz2: true
    
    - name: check conda
      shell: bash -el {0}
      run: |
        conda info
        conda list
    
    - name: check
      shell: bash -el {0}
      run: |
        conda activate ./env
        root-config --version
        cmake --version
